version: "3.9"

services:
  fyle_frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-stage
    container_name: fyle_frontend
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.fyle_frontend.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.fyle_frontend.entrypoints=websecure"
      - "traefik.http.routers.fyle_frontend.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.fyle_frontend.middlewares=traefik-compress"
      - "traefik.http.services.fyle_frontend.loadbalancer.server.port=${NGINX_PORT}"

networks:
  traefik:
    external: true